# See https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops
variables:
    azureSubscriptionEndpoint: Contoso
    azureContainerRegistry: aachongiotregistry.azurecr.io

steps:    

- task: AzureIoTEdge@2
  displayName: AzureIoTEdge - Build module images
  inputs:
    action: Build module images
    templateFilePath: edge/SimulatedEdgeDevice/deployment.template.json
    defaultPlatform: amd64  
- task: AzureIoTEdge@2
  inputs:
    action: 'Push module images'
    containerregistrytype: 'Azure Container Registry'
    azureSubscriptionEndpoint: 'OTA-PRD-1268 (ac48a080-d793-4c8a-b9ed-b0088d9ff1ef)'
    azureContainerRegistry: '{"loginServer":"aachongiotregistry.azurecr.io", "id" : "/subscriptions/ac48a080-d793-4c8a-b9ed-b0088d9ff1ef/resourceGroups/rg-aachong/providers/Microsoft.ContainerRegistry/registries/aachongiotregistry"}'
    templateFilePath: 'edge/SimulatedEdgeDevice/deployment.template.json'
    defaultPlatform: 'amd64'
    fillRegistryCredential: 'true'