# See https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops
variables:
    azureSubscriptionEndpoint: Contoso
    azureContainerRegistry: aachongiotregistry.azurecr.io

steps:    

- task: AzureIoTEdge@2
  displayName: AzureIoTEdge - Build module images
  inputs:
    action: Build module images
    templateFilePath: edge/SimulatedEdgeDevice/deployment.template.json
    defaultPlatform: amd64  
